In [1]:
# Dependencies
import pandas as pd
from sqlalchemy import create_engine
import config

In [2]:
pga_2017_file = "Resources/pga_tour_stats_2017.csv"
pga_2017_df = pd.read_csv(pga_2017_file)
pga_2017_df.head()

,Player,EVENTS_PLAYED,POINTS,NUMBER_OF_WINS,NUMBER_OF_TOP_Tens,POINTS_BEHIND_LEAD,ROUNDS_PLAYED,SG_PUTTING_PER_ROUND,TOTAL_SG:PUTTING,MEASURED_ROUNDS,...,AVG_CARRY_DISTANCE,LONGEST_CARRY_DISTANCE,SHORTEST_CARRY_DISTANCE,AVG_SCORE,TOTAL_STROKES,TOTAL_ROUNDS,MAKES_BOGEY%,BOGEYS_MADE,HOLES_PLAYED,AGE
0,Aaron Baddeley,27,342,0,1,5275.0,84,-0.062,-4.064,66,...,278.2,312.6,237.1,70.850,5518,78,16.24,228,1404,37
1,Aaron Wise,27,1498,1,4,4119.0,82,0.245,17.134,70,...,282.5,314.6,255.7,70.276,5888,84,16.53,250,1512,22
2,Abraham Ancer,29,909,0,5,4708.0,94,-0.052,-4.076,79,...,275.1,305.8,223.5,70.659,6745,96,14.76,255,1728,27
3,Adam Hadwin,24,1054,0,3,4563.0,88,0.145,8.729,60,...,277.7,307.7,246.9,70.750,6280,89,15.61,250,1602,30
4,Adam Schenk,28,239,0,1,5378.0,86,0.130,8.558,66,...,283.0,305.0,236.8,71.370,5683,80,16.88,243,1440,26

In [3]:
pga_2018_file = "Resources/pga_tour_stats_2018.csv"
pga_2018_df = pd.read_csv(pga_2018_file)
pga_2018_df.head()

,Player Name,Rounds,Fairway Percentage,Year,Avg Distance,gir,Average Putts,Average Scrambling,Average Score,Points,Wins,Top 10,Average SG Putts,Average SG Total,SG:OTT,SG:APR,SG:ARG,Money
0,Henrik Stenson,60,75.19,2018,291.5,73.51,29.93,60.67,69.617,868,NaN,5.0,-0.207,1.153,0.427,0.960,-0.027,"$2,680,487"
1,Ryan Armour,109,73.58,2018,283.5,68.22,29.31,60.13,70.758,"1,006",1.0,3.0,-0.058,0.337,-0.012,0.213,0.194,"$2,485,203"
2,Chez Reavie,93,72.24,2018,286.5,68.67,29.12,62.27,70.432,"1,020",NaN,3.0,0.192,0.674,0.183,0.437,-0.137,"$2,700,018"
3,Ryan Moore,78,71.94,2018,289.2,68.80,29.17,64.16,70.015,795,NaN,5.0,-0.271,0.941,0.406,0.532,0.273,"$1,986,608"
4,Brian Stuard,103,71.44,2018,278.9,67.12,29.11,59.23,71.038,421,NaN,3.0,0.164,0.062,-0.227,0.099,0.026,"$1,089,763"

In [4]:
# Columns we want to extract from dataset
pga_2017_cols = ["Player", "ROUNDS_PLAYED", "POINTS", "AVG_SCORE", "NUMBER_OF_WINS", "NUMBER_OF_TOP_Tens", 
                 "AVG_CARRY_DISTANCE", "SG_PUTTING_PER_ROUND"]
pga_2017_transformed_df = pga_2017_df[pga_2017_cols].copy()

# Renaming Columns
pga_2017_transformed_df = pga_2017_transformed_df.rename(columns={"Player": "player",
                                                                  "ROUNDS_PLAYED": "rounds_played_17",
                                                                  "POINTS": "points_17", 
                                                                  "AVG_SCORE": "avg_score_17", 
                                                                  "NUMBER_OF_WINS": "wins_17", 
                                                                  "NUMBER_OF_TOP_Tens": "top_tens_17",
                                                                  "AVG_CARRY_DISTANCE": "avg_carry_distance_17",
                                                                  "SG_PUTTING_PER_ROUND": "sg_putting_per_round_17"})

# Drop data for rows that contain no data at all
pga_2017_transformed_df.dropna(how='any')

pga_2017_transformed_df.set_index("player", inplace=True)
pga_2017_transformed_df.head()

,rounds_played_17,points_17,avg_score_17,wins_17,top_tens_17,avg_carry_distance_17,sg_putting_per_round_17
player,,,,,,,
Aaron Baddeley,84,342,70.850,0,1,278.2,-0.062
Aaron Wise,82,1498,70.276,1,4,282.5,0.245
Abraham Ancer,94,909,70.659,0,5,275.1,-0.052
Adam Hadwin,88,1054,70.750,0,3,277.7,0.145
Adam Schenk,86,239,71.370,0,1,283.0,0.130

In [5]:
# Columns we want to extract from dataset
pga_2018_cols = ["Player Name", "Rounds", "Points", "Average Score", "Wins", "Top 10", "Avg Distance", 
                 "Average SG Putts"]
pga_2018_transformed_df = pga_2018_df[pga_2018_cols].copy()

# Renaming Columns
pga_2018_transformed_df = pga_2018_transformed_df.rename(columns={"Player Name": "player",
                                                                  "Rounds": "rounds_played_18",
                                                                  "Points": "points_18", 
                                                                  "Average Score": "avg_score_18", 
                                                                  "Wins": "wins_18",
                                                                  "Top 10": "top_tens_18", 
                                                                  "Avg Distance": "avg_carry_distance_18",
                                                                  "Average SG Putts": "sg_putting_per_round_18"})
# Drop data for rows that contain no data at all
pga_2018_transformed_df.dropna(how='all')

pga_2018_transformed_df.set_index("player", inplace=True)
pga_2018_transformed_df.head()

,rounds_played_18,points_18,avg_score_18,wins_18,top_tens_18,avg_carry_distance_18,sg_putting_per_round_18
player,,,,,,,
Henrik Stenson,60,868,69.617,NaN,5.0,291.5,-0.207
Ryan Armour,109,"1,006",70.758,1.0,3.0,283.5,-0.058
Chez Reavie,93,"1,020",70.432,NaN,3.0,286.5,0.192
Ryan Moore,78,795,70.015,NaN,5.0,289.2,-0.271
Brian Stuard,103,421,71.038,NaN,3.0,278.9,0.164

In [6]:
# change the data type to a float
pga_2018_transformed_df['rounds_played_18'] = pga_2018_transformed_df[['rounds_played_18']].astype(float)
print(pga_2018_transformed_df.dtypes)

rounds_played_18           float64
points_18                   object
avg_score_18               float64
wins_18                    float64
top_tens_18                float64
avg_carry_distance_18      float64
sg_putting_per_round_18    float64
dtype: object

In [7]:
# taking out the comma's within the column to allow us to change data type
pga_2018_transformed_df['points_18'] = pga_2018_transformed_df['points_18'].str.replace(',', '') 
pga_2018_transformed_df.head()

,rounds_played_18,points_18,avg_score_18,wins_18,top_tens_18,avg_carry_distance_18,sg_putting_per_round_18
player,,,,,,,
Henrik Stenson,60.0,868,69.617,NaN,5.0,291.5,-0.207
Ryan Armour,109.0,1006,70.758,1.0,3.0,283.5,-0.058
Chez Reavie,93.0,1020,70.432,NaN,3.0,286.5,0.192
Ryan Moore,78.0,795,70.015,NaN,5.0,289.2,-0.271
Brian Stuard,103.0,421,71.038,NaN,3.0,278.9,0.164

In [8]:
pga_2018_transformed_df['points_18'] = pga_2018_transformed_df[['points_18']].astype(float)
print(pga_2018_transformed_df.dtypes)

rounds_played_18           float64
points_18                  float64
avg_score_18               float64
wins_18                    float64
top_tens_18                float64
avg_carry_distance_18      float64
sg_putting_per_round_18    float64
dtype: object

In [9]:
# Create a SQL Database connection
connection_string = f"postgres:{config.password}@localhost:5432/pga_tour_stats_db"
engine = create_engine(f'postgresql://{connection_string}')

In [10]:
# checking tables
engine.table_names()

['pga_tour_stats_2017', 'pga_tour_stats_2018']

In [11]:
# Load dataframes into database
try:
    pga_2018_transformed_df.to_sql(name='pga_tour_stats_2018', con=engine, if_exists='append', index=True) 
    print("Data loaded successfully")
    
except:
    print("Data has already been loaded to db")

Data loaded successfully

In [12]:
try:
    pga_2017_transformed_df.to_sql(name='pga_tour_stats_2017', con=engine, if_exists='append', index=True) 
    print("Data loaded successfully")

except:
    print("Data has already been loaded to db")

Data loaded successfully